[package]
name = "pointpca2"
version = "0.5.0"
edition = "2021"

[lib]
name = "pointpca2"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.32.5"
numpy = "0.24.0"
rayon = "1.10.0"

[dependencies.pointpca2-rs]
git = "https://github.com/arthurhscarvalho/pointpca2-rs.git"
tag = "v1.5.0"

[dependencies.pyo3]
version = "0.24.1"
features = ["extension-module"]
